#Flutter Wrapper
-keep class io.flutter.app** { *; }
-keep class io.flutter.plugin** { *; }
-keep class io.flutter.util** { *; }
-keep class io.flutter.view** { *; }
-keep class io.flutter.** { *; }
-keep class io.flutter.plugins** { *; }
-keep class com.adyen.checkout.base.model.** { *; }
-keep class com.adyen.threeds2.** { *; } 
-keep public class com.adyen.ui.DefaultPaymentRequestListener {*;}
-keep public class com.adyen.ui.DefaultPaymentRequestDetailsListener {*;}
